#!/bin/sh -e

cd $(dirname $0)/..
IMAGE_NAME="hello-demo"
REPO_PREFIX="devopsession"
TAG_TIME=$(export TZ=UTC-8; date +'%Y%m%d%H%M')

DOCKER_USER="devopsession"
DOCKER_PASS="devopsession"

./auto/build-docker-image

# Release
echo ">>> Release to registry <<<"
docker tag ${REPO_PREFIX}/${IMAGE_NAME} ${REPO_PREFIX}/${IMAGE_NAME}:${TAG_TIME}

echo ">>> Login to registry <<<"
docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

docker push ${REPO_PREFIX}/${IMAGE_NAME}
docker push ${REPO_PREFIX}/${IMAGE_NAME}:${TAG_TIME}
echo ">>> Pushed docker image ${REPO_PREFIX}/${IMAGE_NAME} with tags ${TAG_TIME}, latest <<<"
